### ISSUE TITLE
Reason behind starting service in container start?

### ISSUE THREAD

**Issue by richardgavel** [Microsoft/mssql-docker#147]
I'm wondering what the reason behind putting the start of the SQL Server service in the container startup is, versus having it already running within the image itself?

**Comment by twright-msft** [comment]
Are you referring to the Windows container images?

**Comment by richardgavel** [comment]
Yes I am.

**Comment by twright-msft** [comment]
OK, SQL Server on Windows has been something that has run as a Windows service primarily for a long time.  It wasnt really designed to run as a process except for a few specific troubleshooting and configuration scenarios.  For now it runs as a Windows service because "that's how it's always been".  The SQL Server on Linux images have SQL Server running as a process as you would expect.  As we come around to investing more in SQL Server in Windows containers at some point we will change it to be a process-based container image there too.
