### ISSUE TITLE
SQL Server 2017 Windows container image

### ISSUE THREAD

**Issue by nels** [Microsoft/mssql-docker#175]
The Linux container is up to date but the Windows container is stuck at 2016

**Comment by twright-msft** [comment]
Are you looking here?
https://hub.docker.com/r/microsoft/mssql-server-windows-express/tags/
https://hub.docker.com/r/microsoft/mssql-server-windows-developer/tags/

**Comment by mi-hol** [comment]
@twright-msft I saw the same issue in this repository:
mssql-docker/windows/mssql-server-windows-developer/dockerfile
as it still refers to the 2016 version
'# SQL Server 2016 Developer SP1:
ENV exe "https://go.microsoft.com/fwlink/?linkid=840945"
ENV box "https://go.microsoft.com/fwlink/?linkid=840944"'

in case these artefacts are replaced (aka obsoleted) by the link you mentioned above, readme.md and other files in the repository should be updated to reflect this change :)
Otherwise people will be mislead by inconsistent information.

**Comment by perrysk-msft** [comment]
Thanks @mi-hol! The image links that @twright-msft noted above contain SQL 2017 Express and Developer respectively. We just missed updating the comment above that says 2016 version. 

These are now updated to avoid further confusion.
