### ISSUE TITLE
mssql-server-windows image missing on docker hub?

### ISSUE THREAD

**Issue by julielerman** [Microsoft/mssql-docker#182]
The mssql-server-windows image doesn't' have a page on docker hub. The others (linux, express, developer) are easily found.

I can't find it via search and when I try to go to directly to https://hub.docker.com/r/microsoft/mssql-server-windows/, I get a 404.

Is that intentional? Should I just be using the docker file from this repo instead?

**Comment by perrysk-msft** [comment]
Thanks @julielerman.

This is indeed intentional. We stopped using the mssql-server-windows Docker Hub repo as soon as we GA'd SQL 2017. Please use the following Linux, Express, and Developer images on Docker Hub.

https://hub.docker.com/r/microsoft/mssql-server-linux/
https://hub.docker.com/r/microsoft/mssql-server-windows-developer/
https://hub.docker.com/r/microsoft/mssql-server-windows-express/

**Comment by amitbhsingh** [comment]
@perrysk-msft  those links are dead too :(

**Comment by icnocop** [comment]
See https://github.com/microsoft/mssql-docker/issues/799
