### ISSUE TITLE
Cannot attach dbs by attach_dbs at mssql-server-linux

### ISSUE THREAD

**Issue by DawidSadlik** [Microsoft/mssql-docker#242]
Cannot attach database files by attach_dbs env on linux image. Is it possible?

**Comment by perrysk-msft** [comment]
@attach_dbs is currently only available in Windows container SQL images.

**Comment by KevM** [comment]
Can we get an explanation as to why this is currently different between Windows and Linux SQL Server images? What is the desired workaround?

**Comment by twright-msft** [comment]
@perrysk-msft implemented attach_dbs as an experiment to see if that would be useful on Windows containers.  It is implemented using PowerShell scripting in the entrypoint.  We could do something similar on the Linux container side using bash scripts or something, but our longer term goal is to implement this as something that is actually part of the engine that is executed on sqlservr start.  We'll get to that eventually but it is backlogged behind other priorities right now.  In the sense of trying to be efficient we're not spending time on a temporary solution in bash scripts on the Linux side.

You can do something like this on your own using an approach similar to what @perrysk-msft did but just use bash scripting instead.  You can see his implementation for Windows here:
https://github.com/Microsoft/mssql-docker/tree/master/windows/mssql-server-windows
You'll see that the CMD in the Dockerfile runs the start.ps1 PowerShell.  Inside of the start.ps1 you'll see how he parses the JSON that is passed in via the env variable.

If you dont really care about it being parameterized as an env var so that it can be used in different situations you can try an implementation similar to this:
https://github.com/twright-msft/mssql-node-docker-demo-app
