### ISSUE TITLE
mssql-server package not installed in 2017-latest image

### ISSUE THREAD

**Issue by Spongman** [Microsoft/mssql-docker#265]
came across this while trying to install fts in my 2017-latest container. turns out the `mssql-server` package isn't acually installed in the 2017-latest image, so when you try to install `mssql-server-fts` it tries to re-install it.

````
$ sudo docker run ... --name sql1 -d microsoft/mssql-server-linux:2017-latest
$ sudo docker exec -it sql1 "bash"
# dpk -l sql
dpkg-query: no packages found matching sql
# apt install mssql-server-fts
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  mssql-server
The following NEW packages will be installed:
  mssql-server mssql-server-fts
0 upgraded, 2 newly installed, 0 to remove and 9 not upgraded.
Need to get 414 MB of archives.
After this operation, 1502 MB of additional disk space will be used.
Do you want to continue? [Y/n]
````

i would have expected the image to alread have the `mssql-server` package installed.

why isn't it installed using something more like https://github.com/Microsoft/mssql-docker/blob/master/linux/preview/examples/mssql-agent-fts-ha-tools/Dockerfile ?

**Comment by twright-msft** [comment]
The mssql-server-linux image uses a Dockerfile like this one: https://github.com/Microsoft/mssql-docker/blob/master/linux/mssql-server-linux/Dockerfile 

The SQL Server files are simply copied into the image using COPY instead of doing a package install.  Our build process automation just picks up the files that are output from the build and puts them in the image.
