### ISSUE TITLE
Start in single user mode: microsoft/mssql-server-linux:2017-latest

### ISSUE THREAD

**Issue by KELightsey** [Microsoft/mssql-docker#348]
I need to start microsoft/mssql-server-linux:2017-latest in single user mode so I can restore the [master] database. I have looked at the URL's below for options with the sql conf file as well as environment variables, and I've attempted to just start the image with the "-m" option but have been unsuccessful. How can I start SQL Server Linux in Docker in single user mode?
Thanks,
Katherine

https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-mssql-conf?view=sql-server-2017
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-2017

**Comment by twright-msft** [comment]
Have you tried to [override ](https://docs.docker.com/engine/reference/run/#cmd-default-command-or-options)the CMD by running "/opt/mssql/bin/sqlservr -m"?

**Comment by KELightsey** [comment]
Travis Write,
 Thanks for the suggestion. I just tried your recommendation (I believe; I should mention that I am new to Docker, although not new to SQL Server).

 I created a container as:
docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=<secure_password>' -p 1390:1433 -d --name=dmt_00 microsoft/mssql-server-linux:2017-latest

 I then committed that container as an image with the change as:
docker commit --change='CMD "/opt/mssql/bin/sqlservr -m"' container dmt_00 kate/dmt_00__single_user_mode

 I then started that image as a new container. I opened SSMS, connected to the just started SQL Server instance, and attempted to restore [master], but got the usual error message that it could not be set in SINGLE_USER mode. Of course we know that, my intention was to start the instance in SINGLE_USER mode, but clearly that didn't happen. 

 As noted, I'm new to Docker. I need to set up some development and integration test environments for the development team for which I'm acting DBA and "everything SQL", and thought that Docker would be a leaner option than Hyper V or VMWare. 

 I would appreciate suggestions,

Thanks,
Kate

**Comment by twright-msft** [comment]
I'm not sure if that way would work. What I had in mind was this:
`docker run -e ACCEPT_EULA=Y -e SA_PASSWORD=SomePassword1234 -p 1433:1433 -d microsoft/mssql-server-linux:2017-latest "/opt/mssql/bin/sqlservr" "-m"`

I tested this on my mac and used the -it parameter to the docker run command to see the output in the logs and I did see the statement in there that the -m parameter had indeed been passed in and it said that it was starting in single user mode.

**Comment by KELightsey** [comment]
Travis, thanks for your help. This did get the instance started in single user mode on my Windows 10 client. I haven't tried restoring [master] yet as I have been working to resolve other issues. The final straw is not being able to restore a database over a certain size. I just posted on another forum here about that. 

I like the concept, but SQL on Linux in Docker is clearly a pre-beta release. I'm going to just use either VMWare or HyperV with Windows clients.

Thanks again for your help,
K

![untitled](https://user-images.githubusercontent.com/464499/44232175-1e73d580-a155-11e8-8448-0bc1798c7aca.jpg)

**Comment by twright-msft** [comment]
Yeah, SQL on Linux containers on Linux is a much better experience right now and we even support customers in production in that configuration SQL on Linux containers on Windows has some problems still due to the underlying Linux container hosting on Windows layers, especially when it comes to mounting volumes.  SQL on Windows containers on Windows is really just experimental at the moment, but we are working on some official SQL on Windows containers that are more ready for prime time now.
If your primary dev/test environment for using SQL Server in containers is Windows and you are trying to do anything with mounted volumes right now, I definitely recommend just using a VM for a few more months.  

Glad to hear that you were able to get the container started in single user mode.  I'll request that we add this method of passing startup cmdline parameters to the documentation.  I'll go ahead and close this issue since we were able to figure out how to start SQL in single user mode in a container.
