### ISSUE TITLE
Docker image for 2017 shows version 15

### ISSUE THREAD

**Issue by guillemsola** [Microsoft/mssql-docker#433]
I'm trying to use the 2017 version as per https://hub.docker.com/r/microsoft/mssql-server-linux/.

I different 2017 versions but on start log says it is 2019 CTP 

for instance, if I use

`dockerfile
FROM mcr.microsoft.com/mssql/server:2017-CU12-ubuntu
`

when I do `select @@version` I get

`
Microsoft SQL Server 2019 (CTP2.3) - 15.0.1300.359 (X64)   Feb 15 2019 23:50:43   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Linux (Ubuntu 16.04.5 LTS) <X64>
`

How can I get a Docker image with 2017 from the new repository?

**Comment by forkazmoden** [comment]
Hi,

```
# Base OS layer: Latest Ubuntu LTS.
FROM ubuntu:16.04

# Default SQL Server TCP/Port.
EXPOSE 1433

# Copy all SQL Server runtime files from build drop into image.
COPY ./install /

# Run SQL Server process.
CMD [ "/opt/mssql/bin/sqlservr" ]
```
When you use this dockerfile to build the image, it will copy the install files from your build and drop it into the image. I think the runtime files you used is the SQL Server 2019 package files.

In order to pull the SQL Server 2017 image, you can use the following command. Please refer to[ Run SQL Server container images with Docker](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-bash).
`docker pull mcr.microsoft.com/mssql/server:2017-latest`

**Comment by guillemsola** [comment]
Ok I guess I found what was the fault on my side.  I want to enable FTS capabilities and this is updating 

```
RUN wget -qO- https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-preview.list > /etc/apt/sources.list.d/mssql.list && apt update && apt install -y mssql-server-fts
```

I must use `mssql-server-2017.list` otherwise the whole server instance also gets updated.
