### ISSUE TITLE
SQL server license issue on Kubernetes

### ISSUE THREAD

**Issue by simoncho** [microsoft/mssql-docker#509]
The SQL server license guide is telling that "License only the cores configured for access"
https://download.microsoft.com/download/B/C/0/BC0B2EA7-D99D-42FB-9439-2C56880CAFF4/SQL_Server_2017_Licensing_Datasheet.pdf

The problem is that, even if Kubernetes limit the CPU up to 4 for SQL server, SQL server will utilized all core up to 400% CPU.

Ex) Worker node 12 cores. SQL Pods CPU limit is 4. It will utilize CPU like this.
CPU 0: 33%
CPU 1: 33%
CPU 2: 33%
CPU 3: 33%
CPU 4: 33%
CPU 5: 33%
CPU 6: 33%
CPU 7: 33%
CPU 8: 33%
CPU 9: 33%
CPU 10: 33%
CPU 11: 33%

Total : 400 % (=12*33%)

That's how designed on Container area.

Because, Container doesn't have OS. It pretty much accesses all nodes resource up to Pods resource limitation.
Based on the current license model, does it need to pay 12 core licenses?

It could be considered. Otherwise, SQL server on Kubernetes would be challenge.

**Comment by DiomedesDominguez** [comment]
Hello, I'm a MS Partner and certified in Microsoft Licensing. 

Here is info on Docker's support [packages](https://www.docker.com/pricing).  As per the article [here](https://blog.docker.com/2016/09/docker-microsoft-partnership/), Microsoft partnered with Docker to provide enterprise support at no additional cost to Server 2016 customers.

**Comment by PatrickLang** [comment]
Linux or Windows?

**Comment by PatrickLang** [comment]
Linux can reserve and restrict cores using this approach:
https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#static-policy

I'm not a lawyer/licensing expert, but that's the feature I would try to restrict to specific cores.

**Comment by amitmsft** [comment]
We have updated our licensing document to cover how containers can be licensed. You now have the ability to license the cores assigned to the container similar to virtual machines. 

Reference: https://aka.ms/sql2019licenseguide

**Comment by SimonNowcom** [comment]
Thanks you for the update regarding License.

I'll create another issue regarding the cpuset related.

Just for the quick note, 
Static-policy in K8s is option for node setting. It is not for the deployment setting.
It is also beta by the way.

k8s Deployment doesn't support CPUSET option in docker.
So, express edition and standard edition would have problem to use all underline hardware resource if CPU cores are more than socket or core limit.

https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#static-policy
is only can do by Node. Not for deployment.

Note: CPU Manager doesn’t support offlining and onlining of CPUs at runtime. Also, if the set of online CPUs changes on the node, the node must be drained and CPU manager manually reset by deleting the state file cpu_manager_state in the kubelet root directory.

**Comment by trootnev** [comment]
Sorry, but it is still absolutely unclear to me how do we license SQL Server on kubernetes since there is no way to limit the number of cores MSSQL "sees" when started in k8s pod. I've set up a minikube env and experimented with CPU manager and was able to limit a pod to use only one specific CPU on on the node with 4 cores. Still if we go to errorlog then we will see that SQL Server thinks it has 4 cores. 
If I read licensing guide for containers directly, it says that all the virtual cores need to be licensed, period. Looks like this was made with docker in mind only.
We want to run multiple instances of SQL Server 2019 standard edition in kubernetes. We are not allowed to license all the physical cores on the node since we dont have Enterprise Edition and we follow licensing guide directly then to run 4 SQL Server's with 4 cores set up as a resource limit on the node with 16 cores then we have to buy 16x4 licenses because all of those 4 instances will see all 16 cores from within SQL Server.
Now the question: Am I right with my assumption that without reducing the number of cores visible to MSSQL we need to license all the cores of the node, no matter what we set up as a limit in pod definition? If not, please provide any explicit official statement.
