### ISSUE TITLE
[Question] Does the `:latest` image also have the latest patches/security updates?

### ISSUE THREAD

**Issue by MartinThoma** [microsoft/mssql-docker#670]
I see that MSSQL Server 2019 had an update in October 2020 ([source](https://sqlserverupdates.com/sql-server-2019-updates/)), but the Docker image was updated the last time in October 2020 ([source](https://hub.docker.com/_/microsoft-mssql-server?tab=description)). Hence I guess it contains the latest updates and does not require additional patching. Is that assumption correct?

Does the `:latest` image always have the latest security updates? Is there maybe even an automated process in place to generate the latest image?

**Comment by hlovdal** [comment]
There is a similar issue with server 2017. https://hub.docker.com/_/microsoft-mssql-server lists `2017-CU21-ubuntu-16.04` as the latest version while https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes?view=sql-server-ver15  has two newer `CU22` and `CU22-GDR` entries.

Running `docker pull mcr.microsoft.com/mssql/server:2017-CU22-ubuntu-16.04` works fine but `2017-CU22-GDR-ubuntu-16.04` (my guess) is not a recognized tag. `2017-CU22-ubuntu-16.04` happens to be exactly what `2017-latest` pointed to from when last time that tag was pulled. Pulling latest today moves it from the 4 months old CU22 image to a 6 weeks old image.

So obviously docker hub page has not been updated with the latest tag information even though they exists (not sure of about CU22-GDR though).

And speaking of updating that web page, can you please, please use [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) for dates instead of that dysfunctional abnormality?

**Comment by amvin87** [comment]
":latest" tag label for SQL server should always install the latest CU for SQL Server and the latest CU should have the latest security updates.
