### ISSUE TITLE
No docker process running after running the image

### ISSUE THREAD

**Issue by yorek** [Microsoft/mssql-docker#70]
Hi

I've just pulled the image from Docker Hub and after executing

`docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 -d microsoft/mssql-server-linux`

I don't have any docker process running.

**Comment by twright-msft** [comment]
You mean that you run `docker ps` you don't see any running containers?
If you run `docker ps -a `do you see the container there?

**Comment by yorek** [comment]
Yep, correct.

If I do `docker ps -a` I can see the container but it says "Exited (1) 2 seconds ago"

**Comment by twright-msft** [comment]
Ok, sounds like the sqlservr process is crashing on startup.  Can you please try running `docker run -it ....` instead of `docker run -d ...`?  That will allow you to see the stdout and look for failures.  One common problem is that you don't have enough RAM allocated to your Linux Moby VM if you are using Docker for Mac or Docker for Windows.  You can configure the amount of RAM for the VM through the settings if you are using Docker for Mac or Docker for Windows.

**Comment by yorek** [comment]
yep, you got it, it says "This machine must have at least 3.25 gigabytes of memory to install Microsoft(R) SQL Server(R)."

It may be useful to mention this requirement and how to set the memory used by Docker in the readme file.
